version: "3"

services:
  web:
    build: ./web
    image: public.ecr.aws/prima/bookshelf-remove-after-lab:2.0.0
    container_name: web
    restart: always
    networks:
      - bookshelf
    environment:
      - PORT=5000
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=0
      - TZ=Europe/Rome
    expose:
      - 5000
    volumes:
      - /tmp:/tmp
    depends_on:
      - cache
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  cache:
    image: public.ecr.aws/prima/redis:6.2.5-3
    restart: always
    container_name: cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - bookshelf

networks:
  bookshelf:
