apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "chart.commonLabels" . | indent 2 }}
    {{- if .Values.additionalLabels }}
    {{ toYaml .Values.additionalLabels}}
    {{- end }}
spec:
  {{- if not .Values.autoscaling }}
  replicas: 3
  {{- end }}
  selector:
    matchLabels:
        app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: {{ .Values.image }}
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-redis
              key: REDIS_PASS
        - name: TZ
          value: Europe/Rome
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
