apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
{{- if .Values.commonLabels}}
{{ toYaml .Values.commonLabels | indent 4}}
{{- end }}
spec:
  replicas: 3
  selector:
    matchLabels:
        app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: public.ecr.aws/prima/bookshelf-remove-after-lab:2.0.0
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PASS
        - name: TZ
          value: Europe/Rome
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
