apiVersion: v1
data:
  REDIS_PASS: {{ required "Please specify a password for Redis (--set redissecret)" .Values.redissecret | toString | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
type: Opaque

