name: helm-linting

on:
  push:
    paths:
      - 'helm/**'

jobs:
  template-charts:
    uses: ./.github/workflows/reusable-helm-linting.yml
    strategy:
      matrix:
        path: [./helm/simple-bookshelf-web, ./helm/simple-bookshelf-web]
        environment: [dev,staging]
        redis-secret: [test-staging123]
    with:
      environment: ${{ matrix.environment }}
      redis-secret: ${{ matrix.redis-secret }}
      path: ${{ matrix.path }}

