name: helm-linting

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  template:
    runs-on: debian
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        run: apt update && apt install curl && curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: template
        working-directory: ./helm/bookshelf-web
        run: helm template . -f values/values.yaml  -f values/${{ inputs.environment }}.yml
